<?php

namespace Database\Seeders;

use App\Models\Categoria;
use App\Models\Ficha;
use App\Models\Lugar;
use App\Models\Zona;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class LugarFichaSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        Ficha::truncate();
        Lugar::truncate();
        Schema::enableForeignKeyConstraints();

        $categorias = Categoria::pluck('id', 'slug');
        $zonas      = Zona::pluck('id', 'slug');

        // Límites geográficos por zona
        $bounds = [
            'atlantida'        => [-34.780, -34.755, -55.795, -55.745],
            'las-toscas'       => [-34.745, -34.720, -55.685, -55.640],
            'parque-del-plata' => [-34.762, -34.738, -55.840, -55.800],
            'pocitos'          => [-34.920, -34.895, -56.180, -56.145],
            'carrasco'         => [-34.880, -34.857, -56.060, -56.020],
            'lagomar'          => [-34.822, -34.800, -55.960, -55.925],
            'minas'            => [-34.392, -34.365, -55.252, -55.220],
        ];

        $coord = function (string $zona) use ($bounds): array {
            [$latS, $latN, $lngW, $lngE] = $bounds[$zona];
            $r = mt_rand() / mt_getrandmax();

            return [
                'lat' => round($latS + $r * ($latN - $latS), 6),
                'lng' => round($lngW + $r * ($lngE - $lngW), 6),
            ];
        };

        // ── Plantillas de horarios reutilizables ────────────────────────────
        $h = [
            'full'           => [['dia_inicio'=>'Lunes','dia_fin'=>'Domingo','apertura'=>'09:00','cierre'=>'21:00','cerrado'=>false]],
            'shop'           => [['dia_inicio'=>'Lunes','dia_fin'=>'Sábado','apertura'=>'10:00','cierre'=>'20:00','cerrado'=>false],['dia_inicio'=>'Domingo','dia_fin'=>null,'apertura'=>null,'cierre'=>null,'cerrado'=>true]],
            'office'         => [['dia_inicio'=>'Lunes','dia_fin'=>'Viernes','apertura'=>'09:00','cierre'=>'18:00','cerrado'=>false],['dia_inicio'=>'Sábado','dia_fin'=>'Domingo','apertura'=>null,'cierre'=>null,'cerrado'=>true]],
            'restaurant'     => [['dia_inicio'=>'Lunes','dia_fin'=>'Domingo','apertura'=>'12:00','cierre'=>'00:00','cerrado'=>false]],
            'rest_closed_mon'=> [['dia_inicio'=>'Martes','dia_fin'=>'Domingo','apertura'=>'12:00','cierre'=>'00:00','cerrado'=>false],['dia_inicio'=>'Lunes','dia_fin'=>null,'apertura'=>null,'cierre'=>null,'cerrado'=>true]],
            'bar'            => [['dia_inicio'=>'Martes','dia_fin'=>'Domingo','apertura'=>'18:00','cierre'=>'02:00','cerrado'=>false],['dia_inicio'=>'Lunes','dia_fin'=>null,'apertura'=>null,'cierre'=>null,'cerrado'=>true]],
            'cafe'           => [['dia_inicio'=>'Lunes','dia_fin'=>'Domingo','apertura'=>'08:00','cierre'=>'22:00','cerrado'=>false]],
            'bakery'         => [['dia_inicio'=>'Lunes','dia_fin'=>'Sábado','apertura'=>'07:00','cierre'=>'20:00','cerrado'=>false],['dia_inicio'=>'Domingo','dia_fin'=>null,'apertura'=>'08:00','cierre'=>'13:00','cerrado'=>false]],
            '24h'            => [['dia_inicio'=>'Lunes','dia_fin'=>'Domingo','apertura'=>'00:00','cierre'=>'23:59','cerrado'=>false]],
            'gym'            => [['dia_inicio'=>'Lunes','dia_fin'=>'Viernes','apertura'=>'07:00','cierre'=>'22:00','cerrado'=>false],['dia_inicio'=>'Sábado','dia_fin'=>null,'apertura'=>'08:00','cierre'=>'20:00','cerrado'=>false],['dia_inicio'=>'Domingo','dia_fin'=>null,'apertura'=>'09:00','cierre'=>'14:00','cerrado'=>false]],
        ];

        $datos = [

            // =====================================================================
            // ORIGINAL 20 BUSINESSES (no modifications)
            // =====================================================================

            // ── Restaurantes ────────────────────────────────────────────────────
            [
                'nombre'      => 'La Parrilla de Don Alberto',
                'descripcion' => 'La mejor parrilla del balneario con cortes premium y atención familiar desde 1985.',
                'direccion'   => 'Av. Artigas 1234',
                'telefono'    => '099 123 456',
                'email'       => 'donalberto@parrilla.com.uy',
                'sitio_web'   => 'https://parrillaalbeerto.com.uy',
                'horarios'    => [
                    ['dia_inicio' => 'Lunes',  'dia_fin' => 'Viernes', 'apertura' => '12:00', 'cierre' => '16:00', 'cerrado' => false],
                    ['dia_inicio' => 'Lunes',  'dia_fin' => 'Viernes', 'apertura' => '20:00', 'cierre' => '00:00', 'cerrado' => false],
                    ['dia_inicio' => 'Sábado', 'dia_fin' => 'Domingo', 'apertura' => '12:00', 'cierre' => '01:00', 'cerrado' => false],
                ],
                'featured'  => true,
                'activo'    => true,
                'plan'      => 'premium',
                'categoria' => 'parrilla',
                'zona'      => 'atlantida',
            ],
            [
                'nombre'      => 'Sushi Nakamura',
                'descripcion' => 'Rolls artesanales y cocina japonesa fusión con ingredientes frescos del día.',
                'direccion'   => 'Bulevar España 890',
                'telefono'    => '098 456 789',
                'email'       => 'hola@sushinakamura.com.uy',
                'sitio_web'   => null,
                'horarios'    => [
                    ['dia_inicio' => 'Martes', 'dia_fin' => 'Domingo', 'apertura' => '19:00', 'cierre' => '23:30', 'cerrado' => false],
                    ['dia_inicio' => 'Lunes',  'dia_fin' => null,      'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'  => true,
                'activo'    => true,
                'plan'      => 'basico',
                'categoria' => 'sushi',
                'zona'      => 'pocitos',
            ],
            [
                'nombre'      => 'Pizzería El Cuartito',
                'descripcion' => 'Pizza a la piedra estilo uruguayo, empanadas y pastas caseras.',
                'direccion'   => 'Av. Bolivia 456',
                'telefono'    => '095 321 654',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => [
                    ['dia_inicio' => 'Lunes', 'dia_fin' => 'Domingo', 'apertura' => '11:00', 'cierre' => '00:00', 'cerrado' => false],
                ],
                'featured'  => false,
                'activo'    => true,
                'plan'      => 'gratuito',
                'categoria' => 'pasta-y-pizza',
                'zona'      => 'carrasco',
            ],
            [
                'nombre'      => 'Bodegón Los Amigos',
                'descripcion' => 'Comida casera, menú del día y las mejores milanesas del departamento.',
                'direccion'   => 'Calle 18 de Julio 345',
                'telefono'    => '094 789 123',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => [
                    ['dia_inicio' => 'Lunes',  'dia_fin' => 'Viernes', 'apertura' => '12:00', 'cierre' => '15:30', 'cerrado' => false],
                    ['dia_inicio' => 'Sábado', 'dia_fin' => 'Domingo', 'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'  => false,
                'activo'    => true,
                'plan'      => 'gratuito',
                'categoria' => 'comida-rapida',   // Bodegón = comida casera rápida
                'zona'      => 'minas',
            ],

            // ── Cafés y Bares ────────────────────────────────────────────────────
            [
                'nombre'      => 'Café del Faro',
                'descripcion' => 'Café de especialidad con tortas artesanales y vista al mar desde 1990.',
                'direccion'   => 'Rambla de los Argentinos 829',
                'telefono'    => '099 741 852',
                'email'       => 'info@cafedelfaro.com.uy',
                'sitio_web'   => 'https://cafedelfaro.com.uy',
                'horarios'    => [
                    ['dia_inicio' => 'Lunes', 'dia_fin' => 'Domingo', 'apertura' => '08:00', 'cierre' => '23:00', 'cerrado' => false],
                ],
                'featured'  => true,
                'activo'    => true,
                'plan'      => 'premium',
                'categoria' => 'cafeteria',
                'zona'      => 'atlantida',
            ],
            [
                'nombre'      => 'Bar La Tosca',
                'descripcion' => 'Bar de playa con cerveza artesanal, picadas y música en vivo los fines de semana.',
                'direccion'   => 'Av. Principal 599',
                'telefono'    => '096 963 741',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => [
                    ['dia_inicio' => 'Martes', 'dia_fin' => 'Domingo', 'apertura' => '10:00', 'cierre' => '01:00', 'cerrado' => false],
                    ['dia_inicio' => 'Lunes',  'dia_fin' => null,      'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'  => false,
                'activo'    => true,
                'plan'      => 'gratuito',
                'categoria' => 'bar',
                'zona'      => 'las-toscas',
            ],
            [
                'nombre'      => 'Lattente Espresso',
                'descripcion' => 'Specialty coffee, brunch y postres artesanales en el corazón de Pocitos.',
                'direccion'   => 'Av. Brasil 5700',
                'telefono'    => '098 852 963',
                'email'       => 'hola@lattente.com.uy',
                'sitio_web'   => null,
                'horarios'    => [
                    ['dia_inicio' => 'Lunes',  'dia_fin' => 'Viernes', 'apertura' => '08:00', 'cierre' => '20:00', 'cerrado' => false],
                    ['dia_inicio' => 'Sábado', 'dia_fin' => 'Domingo', 'apertura' => '09:00', 'cierre' => '21:00', 'cerrado' => false],
                ],
                'featured'  => false,
                'activo'    => true,
                'plan'      => 'basico',
                'categoria' => 'cafeteria',
                'zona'      => 'pocitos',
            ],

            // ── Panaderías y Pastelerías ─────────────────────────────────────────
            [
                'nombre'      => 'Panadería La Espiga de Oro',
                'descripcion' => 'Pan de masa madre, medialunas y facturas recién horneadas cada mañana.',
                'direccion'   => 'Calle Juana de Ibarbourou 456',
                'telefono'    => '095 147 258',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => [
                    ['dia_inicio' => 'Lunes',  'dia_fin' => 'Sábado', 'apertura' => '07:00', 'cierre' => '20:00', 'cerrado' => false],
                    ['dia_inicio' => 'Domingo','dia_fin' => null,      'apertura' => '08:00', 'cierre' => '13:00', 'cerrado' => false],
                ],
                'featured'  => false,
                'activo'    => true,
                'plan'      => 'gratuito',
                'categoria' => 'panaderia',
                'zona'      => 'atlantida',
            ],
            [
                'nombre'      => 'Pastelería Dulce Momento',
                'descripcion' => 'Tortas personalizadas, alfajores y macarons artesanales para cada ocasión.',
                'direccion'   => 'Av. Rivera 1890',
                'telefono'    => '094 369 258',
                'email'       => 'dulcemomento@gmail.com',
                'sitio_web'   => null,
                'horarios'    => [
                    ['dia_inicio' => 'Martes', 'dia_fin' => 'Domingo', 'apertura' => '10:00', 'cierre' => '20:00', 'cerrado' => false],
                    ['dia_inicio' => 'Lunes',  'dia_fin' => null,      'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'  => false,
                'activo'    => true,
                'plan'      => 'basico',
                'categoria' => 'pasteleria',
                'zona'      => 'carrasco',
            ],

            // ── Farmacias ───────────────────────────────────────────────────────
            [
                'nombre'      => 'Farmacia San Jorge',
                'descripcion' => 'Farmacia de turno permanente con atención personalizada y delivery a domicilio.',
                'direccion'   => 'Av. General Rivera 432',
                'telefono'    => '099 258 147',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => [
                    ['dia_inicio' => 'Lunes', 'dia_fin' => 'Domingo', 'apertura' => '00:00', 'cierre' => '23:59', 'cerrado' => false],
                ],
                'featured'  => false,
                'activo'    => true,
                'plan'      => 'gratuito',
                'categoria' => 'farmacia',
                'zona'      => 'atlantida',
            ],
            [
                'nombre'      => 'Dietética El Granero Natural',
                'descripcion' => 'Productos naturales, suplementos y alimentos orgánicos a granel.',
                'direccion'   => 'Av. Batlle y Ordóñez 789',
                'telefono'    => '096 741 963',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => [
                    ['dia_inicio' => 'Lunes',  'dia_fin' => 'Sábado', 'apertura' => '09:00', 'cierre' => '19:30', 'cerrado' => false],
                    ['dia_inicio' => 'Domingo','dia_fin' => null,      'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'  => false,
                'activo'    => true,
                'plan'      => 'gratuito',
                'categoria' => 'dietetica',
                'zona'      => 'minas',
            ],

            // ── Supermercados ────────────────────────────────────────────────────
            [
                'nombre'      => 'Verdulería Don Ramón',
                'descripcion' => 'Frutas y verduras frescas del día, productos de estación y delivery.',
                'direccion'   => 'Calle Los Aromos 234',
                'telefono'    => '095 963 852',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => [
                    ['dia_inicio' => 'Lunes',  'dia_fin' => 'Sábado', 'apertura' => '08:00', 'cierre' => '20:00', 'cerrado' => false],
                    ['dia_inicio' => 'Domingo','dia_fin' => null,      'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'  => false,
                'activo'    => true,
                'plan'      => 'gratuito',
                'categoria' => 'verduleria',
                'zona'      => 'lagomar',
            ],
            [
                'nombre'      => 'Almacén El Rincón',
                'descripcion' => 'Almacén de barrio con fiambres, quesos y productos de campo.',
                'direccion'   => 'Calle Los Pinos 345',
                'telefono'    => '098 147 369',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => [
                    ['dia_inicio' => 'Lunes',  'dia_fin' => 'Sábado', 'apertura' => '08:30', 'cierre' => '21:00', 'cerrado' => false],
                    ['dia_inicio' => 'Domingo','dia_fin' => null,      'apertura' => '09:00', 'cierre' => '14:00', 'cerrado' => false],
                ],
                'featured'  => false,
                'activo'    => true,
                'plan'      => 'gratuito',
                'categoria' => 'almacen',
                'zona'      => 'las-toscas',
            ],

            // ── Salud y Bienestar ────────────────────────────────────────────────
            [
                'nombre'      => 'Gym Evolución',
                'descripcion' => 'Gimnasio con pesas, cardio, clases grupales y personal trainers certificados.',
                'direccion'   => 'Rambla República de México 3344',
                'telefono'    => '099 852 741',
                'email'       => 'info@gymevolucion.com.uy',
                'sitio_web'   => 'https://gymevolucion.com.uy',
                'horarios'    => [
                    ['dia_inicio' => 'Lunes',   'dia_fin' => 'Viernes', 'apertura' => '06:00', 'cierre' => '23:00', 'cerrado' => false],
                    ['dia_inicio' => 'Sábado',  'dia_fin' => null,      'apertura' => '08:00', 'cierre' => '20:00', 'cerrado' => false],
                    ['dia_inicio' => 'Domingo', 'dia_fin' => null,      'apertura' => '09:00', 'cierre' => '18:00', 'cerrado' => false],
                ],
                'featured'  => false,
                'activo'    => true,
                'plan'      => 'basico',
                'categoria' => 'gimnasio',
                'zona'      => 'pocitos',
            ],
            [
                'nombre'      => 'Centro de Yoga Prana',
                'descripcion' => 'Clases de yoga, meditación y mindfulness para todos los niveles.',
                'direccion'   => 'Calle del Mar 2100',
                'telefono'    => '094 258 963',
                'email'       => 'yoga@prana.com.uy',
                'sitio_web'   => null,
                'horarios'    => [
                    ['dia_inicio' => 'Lunes',   'dia_fin' => 'Sábado', 'apertura' => '07:00', 'cierre' => '21:00', 'cerrado' => false],
                    ['dia_inicio' => 'Domingo', 'dia_fin' => null,     'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'  => false,
                'activo'    => true,
                'plan'      => 'gratuito',
                'categoria' => 'yoga-y-meditacion',
                'zona'      => 'atlantida',
            ],

            // ── Servicios Profesionales ──────────────────────────────────────────
            [
                'nombre'      => 'Estudio Contable Pérez & Asociados',
                'descripcion' => 'Contabilidad, BPS, DGI, monotributo y asesoramiento para PyMEs.',
                'direccion'   => 'Av. Artigas 1500, Of. 4',
                'telefono'    => '099 369 741',
                'email'       => 'estudio@perezasociados.com.uy',
                'sitio_web'   => null,
                'horarios'    => [
                    ['dia_inicio' => 'Lunes',  'dia_fin' => 'Viernes', 'apertura' => '09:00', 'cierre' => '18:00', 'cerrado' => false],
                    ['dia_inicio' => 'Sábado', 'dia_fin' => 'Domingo', 'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'  => false,
                'activo'    => true,
                'plan'      => 'basico',
                'categoria' => 'estudio-contable',
                'zona'      => 'atlantida',
            ],
            [
                'nombre'      => 'Estudio Jurídico Morales',
                'descripcion' => 'Derecho laboral, civil y comercial. Primera consulta sin cargo.',
                'direccion'   => 'Calle Ellauri 890, 2do piso',
                'telefono'    => '098 741 258',
                'email'       => 'consultas@moralesabogados.com.uy',
                'sitio_web'   => null,
                'horarios'    => [
                    ['dia_inicio' => 'Lunes',  'dia_fin' => 'Viernes', 'apertura' => '10:00', 'cierre' => '19:00', 'cerrado' => false],
                    ['dia_inicio' => 'Sábado', 'dia_fin' => 'Domingo', 'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'  => false,
                'activo'    => true,
                'plan'      => 'gratuito',
                'categoria' => 'estudio-juridico',
                'zona'      => 'pocitos',
            ],

            // ── Indumentaria y Calzado ───────────────────────────────────────────
            [
                'nombre'      => 'Diseños Valentina',
                'descripcion' => 'Ropa de diseño independiente uruguayo, ediciones limitadas y a medida.',
                'direccion'   => 'Av. Rivera km 14, local 3',
                'telefono'    => '096 258 741',
                'email'       => 'valentina@disenos.com.uy',
                'sitio_web'   => null,
                'horarios'    => [
                    ['dia_inicio' => 'Martes', 'dia_fin' => 'Sábado', 'apertura' => '11:00', 'cierre' => '20:00', 'cerrado' => false],
                    ['dia_inicio' => 'Lunes',  'dia_fin' => null,     'apertura' => null,    'cierre' => null,    'cerrado' => true],
                    ['dia_inicio' => 'Domingo','dia_fin' => null,     'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'  => true,
                'activo'    => true,
                'plan'      => 'basico',
                'categoria' => 'ropa-mujer',
                'zona'      => 'carrasco',
            ],
            [
                'nombre'      => 'Zapatería El Buen Paso',
                'descripcion' => 'Calzado artesanal de cuero, reparación y personalización.',
                'direccion'   => 'Calle Echevarriarza 1122',
                'telefono'    => '095 369 852',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => [
                    ['dia_inicio' => 'Lunes',  'dia_fin' => 'Sábado', 'apertura' => '10:00', 'cierre' => '19:30', 'cerrado' => false],
                    ['dia_inicio' => 'Domingo','dia_fin' => null,     'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'  => false,
                'activo'    => true,
                'plan'      => 'gratuito',
                'categoria' => 'calzado',
                'zona'      => 'atlantida',
            ],
            [
                'nombre'      => 'Outlet Urbano',
                'descripcion' => 'Marcas nacionales con descuentos permanentes en ropa y accesorios.',
                'direccion'   => 'Av. Brasil 2890',
                'telefono'    => '094 963 147',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => [
                    ['dia_inicio' => 'Lunes',   'dia_fin' => 'Sábado', 'apertura' => '10:00', 'cierre' => '21:00', 'cerrado' => false],
                    ['dia_inicio' => 'Domingo', 'dia_fin' => null,     'apertura' => '14:00', 'cierre' => '20:00', 'cerrado' => false],
                ],
                'featured'  => false,
                'activo'    => true,
                'plan'      => 'gratuito',
                'categoria' => 'ropa-mujer',
                'zona'      => 'pocitos',
            ],

            // =====================================================================
            // NEW 100 BUSINESSES
            // =====================================================================

            // ── Automotor ────────────────────────────────────────────────────────
            // 21
            [
                'nombre'      => 'Taller Mecánico Rodríguez',
                'descripcion' => 'Servicio mecánico integral, electrónica automotriz y scanner para todas las marcas.',
                'direccion'   => 'Av. Giannattasio km 24',
                'telefono'    => '099 412 387',
                'email'       => 'taller@rodriguezmecanica.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['office'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'taller-mecanico',
                'zona'        => 'atlantida',
            ],
            // 22
            [
                'nombre'      => 'Gomería Rápida Las Toscas',
                'descripcion' => 'Cambio de cubiertas, alineación y balanceo con equipamiento de última generación.',
                'direccion'   => 'Ruta Interbalnearia km 35',
                'telefono'    => '098 553 214',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'gomeria',
                'zona'        => 'las-toscas',
            ],
            // 23
            [
                'nombre'      => 'Lavadero Express Carrasco',
                'descripcion' => 'Lavado exterior e interior, encerado y pulido de carrocería.',
                'direccion'   => 'Av. Italia 6780',
                'telefono'    => '095 887 432',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'lavadero',
                'zona'        => 'carrasco',
            ],
            // 24
            [
                'nombre'      => 'Repuestos del Este',
                'descripcion' => 'Repuestos originales y alternativos para autos nacionales e importados.',
                'direccion'   => 'Calle Lavalleja 678',
                'telefono'    => '094 331 876',
                'email'       => 'ventas@repuestosdeleste.com.uy',
                'sitio_web'   => 'https://repuestosdeleste.com.uy',
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'basico',
                'categoria'   => 'repuestos',
                'zona'        => 'minas',
            ],
            // 25
            [
                'nombre'      => 'Chapa y Pintura García',
                'descripcion' => 'Reparación de abolladuras, pintura automotriz y tratamiento anticorrosivo.',
                'direccion'   => 'Camino Maldonado 3420',
                'telefono'    => '096 774 512',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['office'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'chapa-y-pintura',
                'zona'        => 'lagomar',
            ],

            // ── Educación ────────────────────────────────────────────────────────
            // 26
            [
                'nombre'      => 'English House Atlántida',
                'descripcion' => 'Academia de inglés para niños, jóvenes y adultos con profesores certificados.',
                'direccion'   => 'Calle Treinta y Tres 210',
                'telefono'    => '099 621 743',
                'email'       => 'info@englishhouse.com.uy',
                'sitio_web'   => 'https://englishhouse.com.uy',
                'horarios'    => $h['office'],
                'featured'    => true,
                'activo'      => true,
                'plan'        => 'basico',
                'categoria'   => 'academia-de-idiomas',
                'zona'        => 'atlantida',
            ],
            // 27
            [
                'nombre'      => 'InfoTech Cursos',
                'descripcion' => 'Cursos de programación, diseño gráfico y ofimática para todas las edades.',
                'direccion'   => 'Av. Artigas 890',
                'telefono'    => '098 432 156',
                'email'       => 'cursos@infotech.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['office'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'informatica',
                'zona'        => 'parque-del-plata',
            ],
            // 28
            [
                'nombre'      => 'Escuela de Música Tempo',
                'descripcion' => 'Clases de guitarra, piano, batería y canto para principiantes y avanzados.',
                'direccion'   => 'Calle Rivera 334',
                'telefono'    => '095 213 876',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'musica-y-arte',
                'zona'        => 'pocitos',
            ],
            // 29
            [
                'nombre'      => 'Clases Particulares Martínez',
                'descripcion' => 'Apoyo escolar en matemáticas, física y química para liceo y preparatorios.',
                'direccion'   => 'Calle Sarandí 456',
                'telefono'    => '094 876 321',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['office'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'apoyo-escolar',
                'zona'        => 'minas',
            ],
            // 30
            [
                'nombre'      => 'Autoescuela Seguridad Vial',
                'descripcion' => 'Clases prácticas y teóricas para libreta de conducir categorías A y B.',
                'direccion'   => 'Ruta 8 km 115',
                'telefono'    => '096 543 219',
                'email'       => 'autoescuela@seguridadvial.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['office'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'autoescuela',
                'zona'        => 'minas',
            ],

            // ── Entretenimiento ──────────────────────────────────────────────────
            // 31
            [
                'nombre'      => 'Cine Plaza Pocitos',
                'descripcion' => 'Salas con sonido Dolby, cartelera actualizada y funciones trasnoche los viernes.',
                'direccion'   => 'Av. Brasil 2680',
                'telefono'    => '099 765 432',
                'email'       => 'cartelera@cineplaza.com.uy',
                'sitio_web'   => 'https://cineplaza.com.uy',
                'horarios'    => $h['full'],
                'featured'    => true,
                'activo'      => true,
                'plan'        => 'premium',
                'categoria'   => 'cine-y-teatro',
                'zona'        => 'pocitos',
            ],
            // 32
            [
                'nombre'      => 'Salón de Fiestas La Celebración',
                'descripcion' => 'Salón para cumpleaños, casamientos y eventos corporativos con catering propio.',
                'direccion'   => 'Camino de las Tropas 1200',
                'telefono'    => '098 321 654',
                'email'       => 'eventos@lacelebracion.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'basico',
                'categoria'   => 'salon-de-fiestas',
                'zona'        => 'carrasco',
            ],
            // 33
            [
                'nombre'      => 'Escape Room Misterio',
                'descripcion' => 'Tres salas temáticas de escape para grupos de 2 a 6 personas.',
                'direccion'   => 'Calle Gaboto 1450',
                'telefono'    => '095 654 321',
                'email'       => 'reservas@escapemisterio.com.uy',
                'sitio_web'   => 'https://escapemisterio.com.uy',
                'horarios'    => $h['bar'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'escape-room',
                'zona'        => 'pocitos',
            ],
            // 34
            [
                'nombre'      => 'Arcade Zone',
                'descripcion' => 'Salón de videojuegos retro y modernos con simuladores de carrera y realidad virtual.',
                'direccion'   => 'Av. Giannattasio km 28',
                'telefono'    => '094 987 654',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'arcade-y-juegos',
                'zona'        => 'lagomar',
            ],

            // ── Farmacias (L2 subcategories) ─────────────────────────────────────
            // 35
            [
                'nombre'      => 'Farmacia Cruz Verde',
                'descripcion' => 'Medicamentos, dermocosméticos y atención farmacéutica con delivery las 24 horas.',
                'direccion'   => 'Av. Artigas 2100',
                'telefono'    => '099 112 334',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['24h'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'farmacia',
                'zona'        => 'parque-del-plata',
            ],
            // 36
            [
                'nombre'      => 'Perfumería Aroma',
                'descripcion' => 'Perfumes importados, maquillaje profesional y productos de belleza.',
                'direccion'   => 'Av. Brasil 2345',
                'telefono'    => '098 776 543',
                'email'       => 'ventas@perfumeriaaroma.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'perfumeria',
                'zona'        => 'pocitos',
            ],
            // 37
            [
                'nombre'      => 'Óptica Visión Clara',
                'descripcion' => 'Lentes recetados, de sol y de contacto con examen visual incluido.',
                'direccion'   => 'Calle 18 de Julio 678',
                'telefono'    => '095 443 221',
                'email'       => 'turnos@visionclara.com.uy',
                'sitio_web'   => 'https://visionclara.com.uy',
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'basico',
                'categoria'   => 'optica',
                'zona'        => 'carrasco',
            ],
            // 38
            [
                'nombre'      => 'Veterinaria Patitas',
                'descripcion' => 'Consultas, vacunas, cirugía y peluquería canina con atención de urgencia.',
                'direccion'   => 'Calle Los Ceibos 190',
                'telefono'    => '096 554 332',
                'email'       => 'patitas@veterinaria.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'veterinaria',
                'zona'        => 'las-toscas',
            ],

            // ── Heladerías (L1, no children — need at least 2) ──────────────────
            // 39
            [
                'nombre'      => 'Heladería Freddo del Este',
                'descripcion' => 'Helado artesanal italiano con más de 40 sabores y postres helados.',
                'direccion'   => 'Rambla de los Argentinos 456',
                'telefono'    => '099 334 556',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => true,
                'activo'      => true,
                'plan'        => 'basico',
                'categoria'   => 'heladerias',
                'zona'        => 'atlantida',
            ],
            // 40
            [
                'nombre'      => 'Heladería Los Sabores',
                'descripcion' => 'Helados cremosos, paletas de fruta natural y tortas heladas por encargo.',
                'direccion'   => 'Av. Principal 320',
                'telefono'    => '098 221 443',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'heladerias',
                'zona'        => 'las-toscas',
            ],
            // 41
            [
                'nombre'      => 'Heladería Dolce Vita',
                'descripcion' => 'Gelato artesanal con ingredientes naturales y opciones veganas.',
                'direccion'   => 'Av. Brasil 3100',
                'telefono'    => '095 667 889',
                'email'       => 'dolcevita@helados.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'heladerias',
                'zona'        => 'pocitos',
            ],

            // ── Hogar y Construcción ─────────────────────────────────────────────
            // 42
            [
                'nombre'      => 'Ferretería El Tornillo',
                'descripcion' => 'Herramientas, bulonería, electricidad y materiales de construcción en general.',
                'direccion'   => 'Av. Artigas 567',
                'telefono'    => '099 876 234',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'ferreteria',
                'zona'        => 'atlantida',
            ],
            // 43
            [
                'nombre'      => 'Pinturería Colores del Sol',
                'descripcion' => 'Pinturas, impermeabilizantes, esmaltes y asesoramiento en color.',
                'direccion'   => 'Calle Lavalleja 234',
                'telefono'    => '098 345 678',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'pintureria',
                'zona'        => 'parque-del-plata',
            ],
            // 44
            [
                'nombre'      => 'Mueblería Don José',
                'descripcion' => 'Muebles de madera maciza, a medida y estándar para todo el hogar.',
                'direccion'   => 'Ruta 8 km 113',
                'telefono'    => '094 567 891',
                'email'       => 'ventas@muebleriadonjose.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'basico',
                'categoria'   => 'muebleria',
                'zona'        => 'minas',
            ],
            // 45
            [
                'nombre'      => 'Barraca Sur',
                'descripcion' => 'Materiales de construcción, arena, portland, hierro y aberturas de aluminio.',
                'direccion'   => 'Camino Carrasco 4500',
                'telefono'    => '096 432 178',
                'email'       => 'info@barracasur.com.uy',
                'sitio_web'   => 'https://barracasur.com.uy',
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'basico',
                'categoria'   => 'barraca',
                'zona'        => 'carrasco',
            ],
            // 46
            [
                'nombre'      => 'Electricidad Total',
                'descripcion' => 'Instalaciones eléctricas, materiales, luminarias y servicio técnico.',
                'direccion'   => 'Av. Giannattasio km 26',
                'telefono'    => '095 321 789',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'electricidad',
                'zona'        => 'lagomar',
            ],
            // 47
            [
                'nombre'      => 'Vivero Jardín Verde',
                'descripcion' => 'Plantas ornamentales, frutales, tierra preparada y macetas artesanales.',
                'direccion'   => 'Camino de los Horneros 890',
                'telefono'    => '099 543 876',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'vivero-y-jardin',
                'zona'        => 'parque-del-plata',
            ],

            // ── Indumentaria y Calzado (L2 subcategories) ───────────────────────
            // 48
            [
                'nombre'      => 'Moda Femenina Lucía',
                'descripcion' => 'Ropa de mujer casual y elegante, accesorios y bijouterie.',
                'direccion'   => 'Av. Rivera 1234',
                'telefono'    => '098 654 321',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'ropa-mujer',
                'zona'        => 'lagomar',
            ],
            // 49
            [
                'nombre'      => 'Caballeros Style',
                'descripcion' => 'Camisas, trajes, pantalones y accesorios masculinos de primeras marcas.',
                'direccion'   => 'Calle Ellauri 456',
                'telefono'    => '095 789 456',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'ropa-hombre',
                'zona'        => 'pocitos',
            ],
            // 50
            [
                'nombre'      => 'Calzados Montevideo',
                'descripcion' => 'Zapatos, zapatillas y botas para toda la familia con marcas nacionales.',
                'direccion'   => 'Av. 18 de Julio 1890',
                'telefono'    => '094 321 876',
                'email'       => 'info@calzadosmvd.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'calzado',
                'zona'        => 'carrasco',
            ],
            // 51
            [
                'nombre'      => 'Sport Life',
                'descripcion' => 'Ropa deportiva, zapatillas running y accesorios fitness de marcas internacionales.',
                'direccion'   => 'Av. Brasil 4200',
                'telefono'    => '096 876 432',
                'email'       => 'ventas@sportlife.com.uy',
                'sitio_web'   => 'https://sportlife.com.uy',
                'horarios'    => $h['shop'],
                'featured'    => true,
                'activo'      => true,
                'plan'        => 'premium',
                'categoria'   => 'deportiva',
                'zona'        => 'pocitos',
            ],
            // 52
            [
                'nombre'      => 'Petit Moda Infantil',
                'descripcion' => 'Ropa para bebés y niños de 0 a 12 años, regalos y accesorios.',
                'direccion'   => 'Calle Los Pinos 678',
                'telefono'    => '099 234 567',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'ropa-infantil',
                'zona'        => 'las-toscas',
            ],

            // ── Panaderías y Pastelerías (L2 confiteria) ─────────────────────────
            // 53
            [
                'nombre'      => 'Confitería El Molino',
                'descripcion' => 'Masas finas, bombones artesanales y tortas para eventos especiales.',
                'direccion'   => 'Av. Rivera 2340',
                'telefono'    => '098 123 876',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['bakery'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'confiteria',
                'zona'        => 'lagomar',
            ],

            // ── Restaurantes (L2 subcategories) ──────────────────────────────────
            // 54
            [
                'nombre'      => 'Restaurante Sabores del Mundo',
                'descripcion' => 'Cocina internacional con platos de Asia, Europa y América en un ambiente moderno.',
                'direccion'   => 'Rambla República de México 2100',
                'telefono'    => '099 876 123',
                'email'       => 'reservas@saboresdelmundo.com.uy',
                'sitio_web'   => 'https://saboresdelmundo.com.uy',
                'horarios'    => $h['rest_closed_mon'],
                'featured'    => true,
                'activo'      => true,
                'plan'        => 'premium',
                'categoria'   => 'cocina-internacional',
                'zona'        => 'pocitos',
            ],
            // 55
            [
                'nombre'      => 'Burger House',
                'descripcion' => 'Hamburguesas gourmet, papas rústicas y batidos artesanales.',
                'direccion'   => 'Av. Italia 4560',
                'telefono'    => '095 432 765',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['restaurant'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'comida-rapida',
                'zona'        => 'carrasco',
            ],

            // ── Cafés y Bares (L2 pub) ───────────────────────────────────────────
            // 56
            [
                'nombre'      => 'The Irish Pub',
                'descripcion' => 'Cerveza importada, whisky irlandés y música en vivo los jueves y sábados.',
                'direccion'   => 'Calle Bacacay 1340',
                'telefono'    => '094 765 432',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['bar'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'pub',
                'zona'        => 'pocitos',
            ],

            // ── Salud y Bienestar (L2 spa-y-estetica) ───────────────────────────
            // 57
            [
                'nombre'      => 'Spa Relax & Belleza',
                'descripcion' => 'Masajes descontracturantes, tratamientos faciales y depilación láser.',
                'direccion'   => 'Av. Brasil 3800',
                'telefono'    => '098 543 210',
                'email'       => 'turnos@sparelax.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'basico',
                'categoria'   => 'spa-y-estetica',
                'zona'        => 'carrasco',
            ],

            // ── Servicios Profesionales (L2 consultoria) ─────────────────────────
            // 58
            [
                'nombre'      => 'Consultoría Digital Innova',
                'descripcion' => 'Marketing digital, posicionamiento web y gestión de redes sociales para PyMEs.',
                'direccion'   => 'Calle Colonia 1890, Of. 8',
                'telefono'    => '096 321 654',
                'email'       => 'hola@innovadigital.com.uy',
                'sitio_web'   => 'https://innovadigital.com.uy',
                'horarios'    => $h['office'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'basico',
                'categoria'   => 'consultoria',
                'zona'        => 'pocitos',
            ],

            // ── Supermercados (L2 subcategories) ─────────────────────────────────
            // 59
            [
                'nombre'      => 'Supermercado El Dorado',
                'descripcion' => 'Supermercado completo con carnicería, fiambrería y productos importados.',
                'direccion'   => 'Av. Giannattasio km 30',
                'telefono'    => '099 654 987',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'basico',
                'categoria'   => 'supermercado',
                'zona'        => 'lagomar',
            ],
            // 60
            [
                'nombre'      => 'Almacén Don Pedro',
                'descripcion' => 'Almacén tradicional con fiambres artesanales, quesos y productos locales.',
                'direccion'   => 'Calle Sarandí 123',
                'telefono'    => '098 765 123',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'almacen',
                'zona'        => 'parque-del-plata',
            ],
            // 61
            [
                'nombre'      => 'Verdulería La Huerta',
                'descripcion' => 'Verduras orgánicas de productores locales, frutas de estación y legumbres.',
                'direccion'   => 'Calle Treinta y Tres 567',
                'telefono'    => '095 876 345',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'verduleria',
                'zona'        => 'atlantida',
            ],
            // 62
            [
                'nombre'      => 'Carnicería Los Gauchos',
                'descripcion' => 'Cortes vacunos, cerdo, cordero y embutidos caseros de primera calidad.',
                'direccion'   => 'Av. Artigas 890',
                'telefono'    => '094 234 567',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'carniceria',
                'zona'        => 'las-toscas',
            ],
            // 63
            [
                'nombre'      => 'Dietética Vida Sana',
                'descripcion' => 'Alimentos sin TACC, suplementos deportivos y productos veganos.',
                'direccion'   => 'Calle Rivera 890',
                'telefono'    => '096 654 321',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'dietetica',
                'zona'        => 'parque-del-plata',
            ],

            // ── Turismo y Alojamiento ────────────────────────────────────────────
            // 64
            [
                'nombre'      => 'Hotel Atlántico',
                'descripcion' => 'Hotel frente al mar con desayuno buffet, piscina y estacionamiento privado.',
                'direccion'   => 'Rambla de los Argentinos 1200',
                'telefono'    => '099 432 876',
                'email'       => 'reservas@hotelatlantico.com.uy',
                'sitio_web'   => 'https://hotelatlantico.com.uy',
                'horarios'    => $h['24h'],
                'featured'    => true,
                'activo'      => true,
                'plan'        => 'premium',
                'categoria'   => 'hotel',
                'zona'        => 'atlantida',
            ],
            // 65
            [
                'nombre'      => 'Hostel Olas del Sur',
                'descripcion' => 'Hostel para mochileros con dormitorios compartidos y privados cerca de la playa.',
                'direccion'   => 'Calle del Mar 340',
                'telefono'    => '098 321 456',
                'email'       => 'info@olasdelsur.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['24h'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'hostel',
                'zona'        => 'parque-del-plata',
            ],
            // 66
            [
                'nombre'      => 'Apart Hotel Brisa Marina',
                'descripcion' => 'Apartamentos equipados con cocina, Wi-Fi y balcón con vista al mar.',
                'direccion'   => 'Av. Principal 780',
                'telefono'    => '095 654 876',
                'email'       => 'reservas@brisamarina.com.uy',
                'sitio_web'   => 'https://brisamarina.com.uy',
                'horarios'    => $h['24h'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'basico',
                'categoria'   => 'apart-hotel',
                'zona'        => 'las-toscas',
            ],
            // 67
            [
                'nombre'      => 'Cabañas del Bosque',
                'descripcion' => 'Cabañas de tronco en entorno natural con parrillero, hamacas y pileta.',
                'direccion'   => 'Camino del Bosque s/n',
                'telefono'    => '094 876 543',
                'email'       => 'cabanas@delbosque.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['24h'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'basico',
                'categoria'   => 'cabanas',
                'zona'        => 'minas',
            ],
            // 68
            [
                'nombre'      => 'Camping Arroyo de los Pájaros',
                'descripcion' => 'Camping con parcelas, baños calientes, parrilleros y acceso al arroyo.',
                'direccion'   => 'Ruta 8 km 120',
                'telefono'    => '096 432 765',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['24h'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'camping',
                'zona'        => 'minas',
            ],

            // =====================================================================
            // ADDITIONAL BUSINESSES TO FILL ZONES AND REACH 120
            // =====================================================================

            // ── More for Parque del Plata (needs more) ──────────────────────────
            // 69
            [
                'nombre'      => 'Parrilla El Fogón Costero',
                'descripcion' => 'Carnes a las brasas, achuras y ensaladas criollas con vista a la rambla.',
                'direccion'   => 'Rambla Parque del Plata 560',
                'telefono'    => '099 567 234',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['restaurant'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'parrilla',
                'zona'        => 'parque-del-plata',
            ],
            // 70
            [
                'nombre'      => 'Café de la Estación',
                'descripcion' => 'Café, medialunas calientes y meriendas caseras en un ambiente tranquilo.',
                'direccion'   => 'Calle Principal 120',
                'telefono'    => '098 876 234',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['cafe'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'cafeteria',
                'zona'        => 'parque-del-plata',
            ],
            // 71
            [
                'nombre'      => 'Panadería Los Trigales',
                'descripcion' => 'Panadería familiar con bizcochos, galletas y pan de campo recién horneado.',
                'direccion'   => 'Av. del Mar 345',
                'telefono'    => '095 234 567',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['bakery'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'panaderia',
                'zona'        => 'parque-del-plata',
            ],
            // 72
            [
                'nombre'      => 'Ferretería Central',
                'descripcion' => 'Herramientas manuales y eléctricas, cerraduras y materiales de plomería.',
                'direccion'   => 'Calle Artigas 234',
                'telefono'    => '094 345 678',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'ferreteria',
                'zona'        => 'parque-del-plata',
            ],
            // 73
            [
                'nombre'      => 'Gimnasio Power Fit',
                'descripcion' => 'Musculación, crossfit y clases de spinning en instalaciones modernas.',
                'direccion'   => 'Av. del Mar 780',
                'telefono'    => '096 567 890',
                'email'       => 'info@powerfit.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['gym'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'gimnasio',
                'zona'        => 'parque-del-plata',
            ],
            // 74
            [
                'nombre'      => 'Taller Mecánico El Pistón',
                'descripcion' => 'Mecánica general, cambio de aceite y diagnóstico computarizado.',
                'direccion'   => 'Ruta Interbalnearia km 42',
                'telefono'    => '099 876 543',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['office'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'taller-mecanico',
                'zona'        => 'parque-del-plata',
            ],

            // ── More for Las Toscas ─────────────────────────────────────────────
            // 75
            [
                'nombre'      => 'Pizzería Napoli',
                'descripcion' => 'Pizzas al horno de leña, calzones y fugazzetas con muzzarella de campo.',
                'direccion'   => 'Av. Principal 890',
                'telefono'    => '098 432 567',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['restaurant'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'pasta-y-pizza',
                'zona'        => 'las-toscas',
            ],
            // 76
            [
                'nombre'      => 'Farmacia Las Toscas',
                'descripcion' => 'Medicamentos, artículos de perfumería y atención farmacéutica personalizada.',
                'direccion'   => 'Calle Los Álamos 123',
                'telefono'    => '095 321 456',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'farmacia',
                'zona'        => 'las-toscas',
            ],
            // 77
            [
                'nombre'      => 'Supermercado La Costa',
                'descripcion' => 'Almacén grande con verdulería, carnicería y productos de limpieza.',
                'direccion'   => 'Av. Principal 234',
                'telefono'    => '094 654 321',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'supermercado',
                'zona'        => 'las-toscas',
            ],
            // 78
            [
                'nombre'      => 'Estudio Contable Vázquez',
                'descripcion' => 'Gestión contable, liquidación de sueldos y trámites ante BPS y DGI.',
                'direccion'   => 'Calle Rivera 456',
                'telefono'    => '096 789 234',
                'email'       => 'contable@vazquez.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['office'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'estudio-contable',
                'zona'        => 'las-toscas',
            ],
            // 79
            [
                'nombre'      => 'Gomería del Balneario',
                'descripcion' => 'Reparación de cubiertas, auxilio mecánico y venta de neumáticos.',
                'direccion'   => 'Ruta Interbalnearia km 36',
                'telefono'    => '099 234 876',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'gomeria',
                'zona'        => 'las-toscas',
            ],
            // 80
            [
                'nombre'      => 'Ferretería del Este',
                'descripcion' => 'Artículos de ferretería, pinturas y materiales para el hogar.',
                'direccion'   => 'Calle Los Eucaliptos 567',
                'telefono'    => '098 567 234',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'ferreteria',
                'zona'        => 'las-toscas',
            ],

            // ── More for Lagomar ─────────────────────────────────────────────────
            // 81
            [
                'nombre'      => 'Parrilla Don Julio',
                'descripcion' => 'Asado con cuero, chorizos caseros y ensaladas de quinta propia.',
                'direccion'   => 'Av. Giannattasio km 25',
                'telefono'    => '099 345 876',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['restaurant'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'parrilla',
                'zona'        => 'lagomar',
            ],
            // 82
            [
                'nombre'      => 'Café & Libro',
                'descripcion' => 'Cafetería con biblioteca libre, tortas caseras y espacio de coworking.',
                'direccion'   => 'Calle Los Robles 234',
                'telefono'    => '098 234 567',
                'email'       => 'hola@cafeylibro.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['cafe'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'cafeteria',
                'zona'        => 'lagomar',
            ],
            // 83
            [
                'nombre'      => 'Panadería El Sol',
                'descripcion' => 'Pan caliente todo el día, tortas fritas los domingos y facturas artesanales.',
                'direccion'   => 'Av. Giannattasio km 27',
                'telefono'    => '095 456 789',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['bakery'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'panaderia',
                'zona'        => 'lagomar',
            ],
            // 84
            [
                'nombre'      => 'Farmacia Lagomar',
                'descripcion' => 'Farmacia con amplio stock, atención las 24 horas y delivery gratuito.',
                'direccion'   => 'Calle Central 456',
                'telefono'    => '094 567 321',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['24h'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'farmacia',
                'zona'        => 'lagomar',
            ],
            // 85
            [
                'nombre'      => 'Lavadero Splash',
                'descripcion' => 'Lavado manual y automático, aspirado interior y limpieza de tapizados.',
                'direccion'   => 'Av. Giannattasio km 24.5',
                'telefono'    => '096 321 876',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'lavadero',
                'zona'        => 'lagomar',
            ],
            // 86
            [
                'nombre'      => 'Veterinaria Mi Mascota',
                'descripcion' => 'Clínica veterinaria con internación, cirugía y venta de alimentos balanceados.',
                'direccion'   => 'Calle Los Sauces 890',
                'telefono'    => '099 876 321',
                'email'       => 'mimascota@vet.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'veterinaria',
                'zona'        => 'lagomar',
            ],
            // 87
            [
                'nombre'      => 'Yoga Studio Lagomar',
                'descripcion' => 'Clases de hatha yoga, vinyasa y meditación guiada en grupos reducidos.',
                'direccion'   => 'Calle Las Margaritas 120',
                'telefono'    => '098 654 789',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['gym'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'yoga-y-meditacion',
                'zona'        => 'lagomar',
            ],

            // ── More for Minas ───────────────────────────────────────────────────
            // 88
            [
                'nombre'      => 'Parrilla El Cerro',
                'descripcion' => 'Restaurante de campo con parrillada completa y vinos de bodega local.',
                'direccion'   => 'Ruta 8 km 112',
                'telefono'    => '094 321 567',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['rest_closed_mon'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'parrilla',
                'zona'        => 'minas',
            ],
            // 89
            [
                'nombre'      => 'Café del Centro',
                'descripcion' => 'Cafetería céntrica con Wi-Fi, desayunos y meriendas a precio accesible.',
                'direccion'   => 'Calle 18 de Julio 234',
                'telefono'    => '096 543 876',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['cafe'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'cafeteria',
                'zona'        => 'minas',
            ],
            // 90
            [
                'nombre'      => 'Farmacia Minas',
                'descripcion' => 'Farmacia céntrica con productos de herboristería y cosmética natural.',
                'direccion'   => 'Av. Lavalleja 456',
                'telefono'    => '099 567 321',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'farmacia',
                'zona'        => 'minas',
            ],
            // 91
            [
                'nombre'      => 'Supermercado El Minuano',
                'descripcion' => 'Supermercado de barrio con precios competitivos y tarjeta de crédito propia.',
                'direccion'   => 'Calle Sarandí 890',
                'telefono'    => '098 321 567',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'supermercado',
                'zona'        => 'minas',
            ],
            // 92
            [
                'nombre'      => 'Hotel Verdún',
                'descripcion' => 'Hotel clásico en el centro de Minas con habitaciones amplias y desayuno incluido.',
                'direccion'   => 'Calle 18 de Julio 567',
                'telefono'    => '094 876 234',
                'email'       => 'reservas@hotelverdun.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['24h'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'basico',
                'categoria'   => 'hotel',
                'zona'        => 'minas',
            ],
            // 93
            [
                'nombre'      => 'Ferretería La Serrana',
                'descripcion' => 'Todo en ferretería, cerrajería y artículos para el campo.',
                'direccion'   => 'Av. Lavalleja 678',
                'telefono'    => '095 432 876',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'ferreteria',
                'zona'        => 'minas',
            ],
            // 94
            [
                'nombre'      => 'Heladería La Serranita',
                'descripcion' => 'Helados artesanales con leche de tambo local y sabores de estación.',
                'direccion'   => 'Calle Rodó 234',
                'telefono'    => '096 234 876',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'heladerias',
                'zona'        => 'minas',
            ],

            // ── More for Carrasco ────────────────────────────────────────────────
            // 95
            [
                'nombre'      => 'Bar Hemingway',
                'descripcion' => 'Coctelería de autor, tapas gourmet y jazz en vivo los viernes.',
                'direccion'   => 'Av. Arocena 1567',
                'telefono'    => '099 432 678',
                'email'       => 'reservas@barhemingway.com.uy',
                'sitio_web'   => 'https://barhemingway.com.uy',
                'horarios'    => $h['bar'],
                'featured'    => true,
                'activo'      => true,
                'plan'        => 'premium',
                'categoria'   => 'bar',
                'zona'        => 'carrasco',
            ],
            // 96
            [
                'nombre'      => 'Gimnasio Iron Club',
                'descripcion' => 'Gimnasio equipado con máquinas de última generación y área de pesas libre.',
                'direccion'   => 'Av. Italia 5200',
                'telefono'    => '098 765 432',
                'email'       => 'info@ironclub.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['gym'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'basico',
                'categoria'   => 'gimnasio',
                'zona'        => 'carrasco',
            ],
            // 97
            [
                'nombre'      => 'Supermercado Disco Carrasco',
                'descripcion' => 'Supermercado completo con sección gourmet, vinoteca y panadería.',
                'direccion'   => 'Av. Italia 6200',
                'telefono'    => '095 876 432',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'supermercado',
                'zona'        => 'carrasco',
            ],
            // 98
            [
                'nombre'      => 'Estudio Jurídico Fernández & Duarte',
                'descripcion' => 'Especialistas en derecho societario, marcas y patentes.',
                'direccion'   => 'Av. Arocena 1200, Of. 3',
                'telefono'    => '094 543 876',
                'email'       => 'estudio@fernandezduarte.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['office'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'estudio-juridico',
                'zona'        => 'carrasco',
            ],
            // 99
            [
                'nombre'      => 'Panadería La Baguette',
                'descripcion' => 'Pan francés, croissants y sándwiches gourmet recién elaborados.',
                'direccion'   => 'Calle Schroeder 890',
                'telefono'    => '096 876 234',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['bakery'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'panaderia',
                'zona'        => 'carrasco',
            ],
            // 100
            [
                'nombre'      => 'Vivero El Jardín de Carrasco',
                'descripcion' => 'Plantas de interior, exterior, paisajismo y servicio de mantenimiento de jardines.',
                'direccion'   => 'Camino Carrasco 3200',
                'telefono'    => '099 321 876',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'vivero-y-jardin',
                'zona'        => 'carrasco',
            ],

            // ── More for Pocitos ─────────────────────────────────────────────────
            // 101
            [
                'nombre'      => 'Parrilla Rambla Sur',
                'descripcion' => 'Cortes especiales a la parrilla con guarniciones gourmet y carta de vinos.',
                'direccion'   => 'Rambla Pocitos 1234',
                'telefono'    => '098 123 456',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['restaurant'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'parrilla',
                'zona'        => 'pocitos',
            ],
            // 102
            [
                'nombre'      => 'Farmacia del Puerto',
                'descripcion' => 'Farmacia moderna con amplio surtido de dermocosméticos y homeopatía.',
                'direccion'   => 'Av. Brasil 3450',
                'telefono'    => '095 234 876',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'farmacia',
                'zona'        => 'pocitos',
            ],
            // 103
            [
                'nombre'      => 'Supermercado Ta-Ta Pocitos',
                'descripcion' => 'Supermercado de cadena con ofertas semanales y tarjeta de beneficios.',
                'direccion'   => 'Av. Brasil 4100',
                'telefono'    => '094 876 321',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'supermercado',
                'zona'        => 'pocitos',
            ],
            // 104
            [
                'nombre'      => 'Panadería Don Pepe',
                'descripcion' => 'Bizcochos y facturas desde las 6 de la mañana, pan de campaña y galletas.',
                'direccion'   => 'Calle Benito Blanco 1456',
                'telefono'    => '096 345 678',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['bakery'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'panaderia',
                'zona'        => 'pocitos',
            ],

            // ── More for Atlántida ───────────────────────────────────────────────
            // 105
            [
                'nombre'      => 'Sushi Bar Atlántida',
                'descripcion' => 'Rolls clásicos y de autor, combos familiares y delivery hasta la playa.',
                'direccion'   => 'Calle 3 esq. Av. Artigas',
                'telefono'    => '099 654 321',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['rest_closed_mon'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'sushi',
                'zona'        => 'atlantida',
            ],
            // 106
            [
                'nombre'      => 'Supermercado El Ancla',
                'descripcion' => 'Supermercado con sección de congelados, bebidas y artículos de limpieza.',
                'direccion'   => 'Av. Artigas 678',
                'telefono'    => '098 432 876',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'supermercado',
                'zona'        => 'atlantida',
            ],
            // 107
            [
                'nombre'      => 'Gimnasio Atlántida Fitness',
                'descripcion' => 'Sala de musculación, funcional y pilates reformer con vista al mar.',
                'direccion'   => 'Rambla de los Argentinos 345',
                'telefono'    => '095 876 234',
                'email'       => 'info@atlantidafitness.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['gym'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'basico',
                'categoria'   => 'gimnasio',
                'zona'        => 'atlantida',
            ],
            // 108
            [
                'nombre'      => 'Óptica del Sol',
                'descripcion' => 'Anteojos de sol, recetados y lentes de contacto con marcas internacionales.',
                'direccion'   => 'Av. Artigas 2300',
                'telefono'    => '094 543 219',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'optica',
                'zona'        => 'atlantida',
            ],
            // 109
            [
                'nombre'      => 'Pastelería La Maison',
                'descripcion' => 'Repostería fina francesa, tartas de fruta y petit fours para eventos.',
                'direccion'   => 'Calle Treinta y Tres 890',
                'telefono'    => '096 432 567',
                'email'       => 'pedidos@lamaison.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['bakery'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'pasteleria',
                'zona'        => 'atlantida',
            ],
            // 110
            [
                'nombre'      => 'Bar de la Playa',
                'descripcion' => 'Cervezas artesanales, tragos tropicales y picadas frente al mar.',
                'direccion'   => 'Rambla de los Argentinos 678',
                'telefono'    => '099 876 432',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['bar'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'bar',
                'zona'        => 'atlantida',
            ],

            // ── Extra businesses to round out ────────────────────────────────────
            // 111
            [
                'nombre'      => 'Consultora Gestión Plus',
                'descripcion' => 'Consultoría en recursos humanos, selección de personal y capacitación.',
                'direccion'   => 'Calle Colonia 2450, Of. 5',
                'telefono'    => '098 321 876',
                'email'       => 'info@gestionplus.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['office'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'consultoria',
                'zona'        => 'carrasco',
            ],
            // 112
            [
                'nombre'      => 'Spa Termas del Este',
                'descripcion' => 'Circuito de agua, sauna, masajes relajantes y tratamientos corporales.',
                'direccion'   => 'Ruta 8 km 118',
                'telefono'    => '094 765 321',
                'email'       => 'reservas@termasdeleste.com.uy',
                'sitio_web'   => 'https://termasdeleste.com.uy',
                'horarios'    => $h['full'],
                'featured'    => true,
                'activo'      => true,
                'plan'        => 'premium',
                'categoria'   => 'spa-y-estetica',
                'zona'        => 'minas',
            ],
            // 113
            [
                'nombre'      => 'Pinturería ArcoIris',
                'descripcion' => 'Pinturas látex, sintéticas, barnices y herramientas de pintura.',
                'direccion'   => 'Calle Los Pinos 890',
                'telefono'    => '095 654 123',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'pintureria',
                'zona'        => 'las-toscas',
            ],
            // 114
            [
                'nombre'      => 'Mueblería Roble',
                'descripcion' => 'Muebles de diseño moderno, colchones y decoración para el hogar.',
                'direccion'   => 'Av. Giannattasio km 29',
                'telefono'    => '096 321 456',
                'email'       => 'ventas@muebleriaroble.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'muebleria',
                'zona'        => 'lagomar',
            ],
            // 115
            [
                'nombre'      => 'Ropa Infantil Cucú',
                'descripcion' => 'Ropa de bebé y niños hasta 10 años, ajuares y regalos para nacimiento.',
                'direccion'   => 'Calle del Mar 456',
                'telefono'    => '099 456 321',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'ropa-infantil',
                'zona'        => 'parque-del-plata',
            ],
            // 116
            [
                'nombre'      => 'Barraca del Norte',
                'descripcion' => 'Ladrillos, bloques, techos, pisos y todo en materiales de obra.',
                'direccion'   => 'Ruta Interbalnearia km 38',
                'telefono'    => '098 876 543',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['shop'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'barraca',
                'zona'        => 'parque-del-plata',
            ],
            // 117
            [
                'nombre'      => 'Confitería Real',
                'descripcion' => 'Alfajores triples, masas secas, bombones y canastas de regalo.',
                'direccion'   => 'Calle 18 de Julio 890',
                'telefono'    => '095 321 876',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['bakery'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'confiteria',
                'zona'        => 'minas',
            ],
            // 118
            [
                'nombre'      => 'English Point',
                'descripcion' => 'Instituto de inglés con preparación para exámenes internacionales FCE y CAE.',
                'direccion'   => 'Av. Brasil 2900',
                'telefono'    => '094 234 876',
                'email'       => 'info@englishpoint.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['office'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'academia-de-idiomas',
                'zona'        => 'carrasco',
            ],
            // 119
            [
                'nombre'      => 'Chapa y Pintura Express',
                'descripcion' => 'Reparaciones rápidas de carrocería, pintura parcial y pulido profesional.',
                'direccion'   => 'Ruta Interbalnearia km 40',
                'telefono'    => '096 876 543',
                'email'       => null,
                'sitio_web'   => null,
                'horarios'    => $h['office'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'chapa-y-pintura',
                'zona'        => 'parque-del-plata',
            ],
            // 120
            [
                'nombre'      => 'Salón de Fiestas Estrella',
                'descripcion' => 'Salón para 200 personas con DJ, iluminación profesional y servicio de catering.',
                'direccion'   => 'Av. Giannattasio km 31',
                'telefono'    => '099 543 678',
                'email'       => 'eventos@salonestrella.com.uy',
                'sitio_web'   => null,
                'horarios'    => $h['full'],
                'featured'    => false,
                'activo'      => true,
                'plan'        => 'gratuito',
                'categoria'   => 'salon-de-fiestas',
                'zona'        => 'lagomar',
            ],
        ];

        foreach ($datos as $data) {
            $zonaSlug      = $data['zona'];
            $categoriaSlug = $data['categoria'];
            $coordenadas   = $coord($zonaSlug);

            $lugar = Lugar::create([
                'nombre'       => $data['nombre'],
                'direccion'    => $data['direccion'],
                'lat'          => $coordenadas['lat'],
                'lng'          => $coordenadas['lng'],
                'categoria_id' => $categorias[$categoriaSlug],
                'zona_id'      => $zonas[$zonaSlug],
                'activo'       => $data['activo'],
            ]);

            Ficha::create([
                'lugar_id'    => $lugar->id,
                'descripcion' => $data['descripcion'],
                'telefono'    => $data['telefono'],
                'email'       => $data['email'],
                'sitio_web'   => $data['sitio_web'],
                'horarios'    => $data['horarios'],   // cast → array, no json_encode manual
                'plan'        => $data['plan'],
                'featured'    => $data['featured'],
                'estado'      => 'activa',
                'activo'      => $data['activo'],
            ]);
        }
    }
}
