<?php

namespace Database\Seeders;

use App\Models\Categoria;
use App\Models\Negocio;
use App\Models\Zona;
use Illuminate\Database\Seeder;

class NegocioSeeder extends Seeder
{
    public function run(): void
    {
        Negocio::truncate();

        $categorias = Categoria::pluck('id', 'slug');
        $zonas      = Zona::pluck('id', 'slug');

        $negocios = [
            // Restaurantes (cat 0) — featured
            [
                'nombre'       => 'La Parrilla de Don Alberto',
                'descripcion'  => 'La mejor parrilla del barrio con cortes premium y atención familiar desde 1985.',
                'direccion'    => 'Av. Corrientes 1234',
                'telefono'     => '011-4321-5678',
                'email'        => 'donalberto@parrilla.com.ar',
                'sitio_web'    => 'https://parrillaalbeerto.com.ar',
                'lat'          => -34.6037,
                'lng'          => -58.3816,
                'horarios'     => [
                    ['dia_inicio' => 'Lunes',  'dia_fin' => 'Viernes', 'apertura' => '12:00', 'cierre' => '16:00', 'cerrado' => false],
                    ['dia_inicio' => 'Lunes',  'dia_fin' => 'Viernes', 'apertura' => '20:00', 'cierre' => '00:00', 'cerrado' => false],
                    ['dia_inicio' => 'Sábado', 'dia_fin' => 'Domingo', 'apertura' => '12:00', 'cierre' => '01:00', 'cerrado' => false],
                ],
                'featured'     => true,
                'activo'       => true,
                'plan'         => 'premium',
                'categoria'    => 'restaurantes',
                'zona'         => 'centro',
            ],
            [
                'nombre'       => 'Sushi Nakamura',
                'descripcion'  => 'Rolls artesanales y cocina japonesa fusión con ingredientes frescos.',
                'direccion'    => 'Thames 890',
                'telefono'     => '011-4833-1122',
                'email'        => 'hola@sushinakamura.com.ar',
                'sitio_web'    => null,
                'lat'          => -34.5895,
                'lng'          => -58.4294,
                'horarios'     => [
                    ['dia_inicio' => 'Martes', 'dia_fin' => 'Domingo', 'apertura' => '19:00', 'cierre' => '23:30', 'cerrado' => false],
                    ['dia_inicio' => 'Lunes',  'dia_fin' => null,      'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'     => true,
                'activo'       => true,
                'plan'         => 'basico',
                'categoria'    => 'restaurantes',
                'zona'         => 'palermo',
            ],
            [
                'nombre'       => 'Pizzería El Cuartito',
                'descripcion'  => 'Pizza al molde estilo porteño, empanadas y pastas caseras.',
                'direccion'    => 'Independencia 456',
                'telefono'     => '011-4300-7890',
                'email'        => null,
                'sitio_web'    => null,
                'lat'          => -34.6188,
                'lng'          => -58.3714,
                'horarios'     => [
                    ['dia_inicio' => 'Lunes', 'dia_fin' => 'Domingo', 'apertura' => '11:00', 'cierre' => '00:00', 'cerrado' => false],
                ],
                'featured'     => false,
                'activo'       => true,
                'plan'         => 'gratuito',
                'categoria'    => 'restaurantes',
                'zona'         => 'san-telmo',
            ],
            [
                'nombre'       => 'Bodegón Los Amigos',
                'descripcion'  => 'Comida casera, menú del día y las mejores milanesas del barrio.',
                'direccion'    => 'Monroe 2345',
                'telefono'     => '011-4784-3311',
                'email'        => null,
                'sitio_web'    => null,
                'lat'          => -34.5591,
                'lng'          => -58.4574,
                'horarios'     => [
                    ['dia_inicio' => 'Lunes',   'dia_fin' => 'Viernes', 'apertura' => '12:00', 'cierre' => '15:30', 'cerrado' => false],
                    ['dia_inicio' => 'Sábado',  'dia_fin' => 'Domingo', 'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'     => false,
                'activo'       => true,
                'plan'         => 'gratuito',
                'categoria'    => 'restaurantes',
                'zona'         => 'belgrano',
            ],
            // Cafés y Bares
            [
                'nombre'       => 'Café Tortoni',
                'descripcion'  => 'Histórico café porteño con shows de tango y medialunas inigualables.',
                'direccion'    => 'Av. de Mayo 829',
                'telefono'     => '011-4342-4328',
                'email'        => 'info@cafetortoni.com.ar',
                'sitio_web'    => 'https://cafetortoni.com.ar',
                'lat'          => -34.6097,
                'lng'          => -58.3793,
                'horarios'     => [
                    ['dia_inicio' => 'Lunes', 'dia_fin' => 'Domingo', 'apertura' => '08:00', 'cierre' => '23:00', 'cerrado' => false],
                ],
                'featured'     => true,
                'activo'       => true,
                'plan'         => 'premium',
                'categoria'    => 'cafes-y-bares',
                'zona'         => 'centro',
            ],
            [
                'nombre'       => 'Bar El Federal',
                'descripcion'  => 'Bar tradicional de San Telmo, buena cerveza artesanal y picadas.',
                'direccion'    => 'Carlos Calvo 599',
                'telefono'     => '011-4300-4313',
                'email'        => null,
                'sitio_web'    => null,
                'lat'          => -34.6218,
                'lng'          => -58.3690,
                'horarios'     => [
                    ['dia_inicio' => 'Martes', 'dia_fin' => 'Domingo', 'apertura' => '10:00', 'cierre' => '01:00', 'cerrado' => false],
                    ['dia_inicio' => 'Lunes',  'dia_fin' => null,      'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'     => false,
                'activo'       => true,
                'plan'         => 'gratuito',
                'categoria'    => 'cafes-y-bares',
                'zona'         => 'san-telmo',
            ],
            [
                'nombre'       => 'Lattente Espresso',
                'descripcion'  => 'Specialty coffee, brunch y postres artesanales en Palermo.',
                'direccion'    => 'El Salvador 5700',
                'telefono'     => '011-4772-1155',
                'email'        => 'hola@lattente.com.ar',
                'sitio_web'    => null,
                'lat'          => -34.5879,
                'lng'          => -58.4380,
                'horarios'     => [
                    ['dia_inicio' => 'Lunes',  'dia_fin' => 'Viernes', 'apertura' => '08:00', 'cierre' => '20:00', 'cerrado' => false],
                    ['dia_inicio' => 'Sábado', 'dia_fin' => 'Domingo', 'apertura' => '09:00', 'cierre' => '21:00', 'cerrado' => false],
                ],
                'featured'     => false,
                'activo'       => true,
                'plan'         => 'basico',
                'categoria'    => 'cafes-y-bares',
                'zona'         => 'palermo',
            ],
            // Panaderías
            [
                'nombre'       => 'Panadería La Espiga de Oro',
                'descripcion'  => 'Pan de masa madre, medialunas y facturas recién horneadas.',
                'direccion'    => 'Alvarez Jonte 3456',
                'telefono'     => '011-4501-2233',
                'email'        => null,
                'sitio_web'    => null,
                'lat'          => -34.6072,
                'lng'          => -58.4890,
                'horarios'     => [
                    ['dia_inicio' => 'Lunes',  'dia_fin' => 'Sábado', 'apertura' => '07:00', 'cierre' => '20:00', 'cerrado' => false],
                    ['dia_inicio' => 'Domingo','dia_fin' => null,      'apertura' => '08:00', 'cierre' => '13:00', 'cerrado' => false],
                ],
                'featured'     => false,
                'activo'       => true,
                'plan'         => 'gratuito',
                'categoria'    => 'panaderias-y-pastelerias',
                'zona'         => 'villa-del-parque',
            ],
            [
                'nombre'       => 'Pastelería Dulce Momento',
                'descripcion'  => 'Tortas personalizadas, alfajores y macarons artesanales.',
                'direccion'    => 'Juramento 1890',
                'telefono'     => '011-4783-6600',
                'email'        => 'dulcemomento@gmail.com',
                'sitio_web'    => null,
                'lat'          => -34.5600,
                'lng'          => -58.4550,
                'horarios'     => [
                    ['dia_inicio' => 'Martes', 'dia_fin' => 'Domingo', 'apertura' => '10:00', 'cierre' => '20:00', 'cerrado' => false],
                    ['dia_inicio' => 'Lunes',  'dia_fin' => null,      'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'     => false,
                'activo'       => true,
                'plan'         => 'basico',
                'categoria'    => 'panaderias-y-pastelerias',
                'zona'         => 'belgrano',
            ],
            // Farmacias
            [
                'nombre'       => 'Farmacia San Jorge',
                'descripcion'  => 'Farmacia de turno permanente con atención personalizada y delivery.',
                'direccion'    => 'Rivadavia 5432',
                'telefono'     => '011-4631-4455',
                'email'        => null,
                'sitio_web'    => null,
                'lat'          => -34.6155,
                'lng'          => -58.4620,
                'horarios'     => [
                    ['dia_inicio' => 'Lunes', 'dia_fin' => 'Domingo', 'apertura' => '00:00', 'cierre' => '23:59', 'cerrado' => false],
                ],
                'featured'     => false,
                'activo'       => true,
                'plan'         => 'gratuito',
                'categoria'    => 'farmacias',
                'zona'         => 'villa-del-parque',
            ],
            [
                'nombre'       => 'Dietética El Granero Natural',
                'descripcion'  => 'Productos naturales, suplementos y alimentos orgánicos a granel.',
                'direccion'    => 'Defensa 789',
                'telefono'     => '011-4362-5544',
                'email'        => null,
                'sitio_web'    => null,
                'lat'          => -34.6235,
                'lng'          => -58.3710,
                'horarios'     => [
                    ['dia_inicio' => 'Lunes', 'dia_fin' => 'Sábado', 'apertura' => '09:00', 'cierre' => '19:30', 'cerrado' => false],
                    ['dia_inicio' => 'Domingo', 'dia_fin' => null,   'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'     => false,
                'activo'       => true,
                'plan'         => 'gratuito',
                'categoria'    => 'farmacias',
                'zona'         => 'san-telmo',
            ],
            // Supermercados
            [
                'nombre'       => 'Verdulería Don Ramón',
                'descripcion'  => 'Frutas y verduras frescas del día, productos de estación y delivery.',
                'direccion'    => 'Nazca 1234',
                'telefono'     => '011-4581-7788',
                'email'        => null,
                'sitio_web'    => null,
                'lat'          => -34.6080,
                'lng'          => -58.4870,
                'horarios'     => [
                    ['dia_inicio' => 'Lunes', 'dia_fin' => 'Sábado', 'apertura' => '08:00', 'cierre' => '20:00', 'cerrado' => false],
                    ['dia_inicio' => 'Domingo', 'dia_fin' => null,   'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'     => false,
                'activo'       => true,
                'plan'         => 'gratuito',
                'categoria'    => 'supermercados',
                'zona'         => 'villa-del-parque',
            ],
            [
                'nombre'       => 'Almacén El Rincón',
                'descripcion'  => 'Almacén de barrio con fiambres, quesos y productos de campo.',
                'direccion'    => 'Tacuarí 345',
                'telefono'     => '011-4343-2211',
                'email'        => null,
                'sitio_web'    => null,
                'lat'          => -34.6190,
                'lng'          => -58.3730,
                'horarios'     => [
                    ['dia_inicio' => 'Lunes',   'dia_fin' => 'Sábado', 'apertura' => '08:30', 'cierre' => '21:00', 'cerrado' => false],
                    ['dia_inicio' => 'Domingo', 'dia_fin' => null,     'apertura' => '09:00', 'cierre' => '14:00', 'cerrado' => false],
                ],
                'featured'     => false,
                'activo'       => true,
                'plan'         => 'gratuito',
                'categoria'    => 'supermercados',
                'zona'         => 'san-telmo',
            ],
            // Salud y Bienestar
            [
                'nombre'       => 'Gym Evolución',
                'descripcion'  => 'Gimnasio con pesas, cardio, clases grupales y personal trainers.',
                'direccion'    => 'Av. Santa Fe 3344',
                'telefono'     => '011-4826-0099',
                'email'        => 'info@gymevolucion.com.ar',
                'sitio_web'    => 'https://gymevolucion.com.ar',
                'lat'          => -34.5888,
                'lng'          => -58.4100,
                'horarios'     => [
                    ['dia_inicio' => 'Lunes',   'dia_fin' => 'Viernes', 'apertura' => '06:00', 'cierre' => '23:00', 'cerrado' => false],
                    ['dia_inicio' => 'Sábado',  'dia_fin' => null,      'apertura' => '08:00', 'cierre' => '20:00', 'cerrado' => false],
                    ['dia_inicio' => 'Domingo', 'dia_fin' => null,      'apertura' => '09:00', 'cierre' => '18:00', 'cerrado' => false],
                ],
                'featured'     => false,
                'activo'       => true,
                'plan'         => 'basico',
                'categoria'    => 'salud-y-bienestar',
                'zona'         => 'palermo',
            ],
            [
                'nombre'       => 'Centro de Yoga Prana',
                'descripcion'  => 'Clases de yoga, meditación y mindfulness para todos los niveles.',
                'direccion'    => 'Scalabrini Ortiz 2100',
                'telefono'     => '011-4774-3322',
                'email'        => 'yoga@prana.com.ar',
                'sitio_web'    => null,
                'lat'          => -34.5920,
                'lng'          => -58.4230,
                'horarios'     => [
                    ['dia_inicio' => 'Lunes',   'dia_fin' => 'Sábado', 'apertura' => '07:00', 'cierre' => '21:00', 'cerrado' => false],
                    ['dia_inicio' => 'Domingo', 'dia_fin' => null,     'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'     => false,
                'activo'       => true,
                'plan'         => 'gratuito',
                'categoria'    => 'salud-y-bienestar',
                'zona'         => 'palermo',
            ],
            // Servicios Profesionales
            [
                'nombre'       => 'Estudio Contable Pérez & Asociados',
                'descripcion'  => 'Contabilidad, impuestos, monotributo y asesoramiento para PyMEs.',
                'direccion'    => 'Lavalle 1500, 4to piso',
                'telefono'     => '011-4382-6677',
                'email'        => 'estudio@perezasociados.com.ar',
                'sitio_web'    => null,
                'lat'          => -34.6040,
                'lng'          => -58.3840,
                'horarios'     => [
                    ['dia_inicio' => 'Lunes', 'dia_fin' => 'Viernes', 'apertura' => '09:00', 'cierre' => '18:00', 'cerrado' => false],
                    ['dia_inicio' => 'Sábado','dia_fin' => 'Domingo', 'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'     => false,
                'activo'       => true,
                'plan'         => 'basico',
                'categoria'    => 'servicios-profesionales',
                'zona'         => 'centro',
            ],
            [
                'nombre'       => 'Estudio Jurídico Morales',
                'descripcion'  => 'Derecho laboral, civil y comercial. Primera consulta sin cargo.',
                'direccion'    => 'Tucumán 890, 2do piso',
                'telefono'     => '011-4326-8899',
                'email'        => 'consultas@moralesabogados.com.ar',
                'sitio_web'    => null,
                'lat'          => -34.6015,
                'lng'          => -58.3800,
                'horarios'     => [
                    ['dia_inicio' => 'Lunes', 'dia_fin' => 'Viernes', 'apertura' => '10:00', 'cierre' => '19:00', 'cerrado' => false],
                    ['dia_inicio' => 'Sábado','dia_fin' => 'Domingo', 'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'     => false,
                'activo'       => true,
                'plan'         => 'gratuito',
                'categoria'    => 'servicios-profesionales',
                'zona'         => 'centro',
            ],
            // Indumentaria
            [
                'nombre'       => 'Diseños Valentina',
                'descripcion'  => 'Ropa de diseño independiente, ediciones limitadas y a medida.',
                'direccion'    => 'Honduras 4567',
                'telefono'     => '011-4831-5566',
                'email'        => 'valentina@disenos.com.ar',
                'sitio_web'    => null,
                'lat'          => -34.5870,
                'lng'          => -58.4320,
                'horarios'     => [
                    ['dia_inicio' => 'Martes', 'dia_fin' => 'Sábado', 'apertura' => '11:00', 'cierre' => '20:00', 'cerrado' => false],
                    ['dia_inicio' => 'Lunes',  'dia_fin' => null,     'apertura' => null,    'cierre' => null,    'cerrado' => true],
                    ['dia_inicio' => 'Domingo','dia_fin' => null,     'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'     => true,
                'activo'       => true,
                'plan'         => 'basico',
                'categoria'    => 'indumentaria-y-calzado',
                'zona'         => 'palermo',
            ],
            [
                'nombre'       => 'Zapatería El Buen Paso',
                'descripcion'  => 'Calzado artesanal de cuero, reparación y personalización.',
                'direccion'    => 'Belgrano 1122',
                'telefono'     => '011-4300-4477',
                'email'        => null,
                'sitio_web'    => null,
                'lat'          => -34.6200,
                'lng'          => -58.3750,
                'horarios'     => [
                    ['dia_inicio' => 'Lunes', 'dia_fin' => 'Sábado', 'apertura' => '10:00', 'cierre' => '19:30', 'cerrado' => false],
                    ['dia_inicio' => 'Domingo','dia_fin' => null,    'apertura' => null,    'cierre' => null,    'cerrado' => true],
                ],
                'featured'     => false,
                'activo'       => true,
                'plan'         => 'gratuito',
                'categoria'    => 'indumentaria-y-calzado',
                'zona'         => 'san-telmo',
            ],
            [
                'nombre'       => 'Outlet Urbano',
                'descripcion'  => 'Marcas nacionales con descuentos permanentes en ropa y accesorios.',
                'direccion'    => 'Av. Cabildo 2890',
                'telefono'     => '011-4787-0011',
                'email'        => null,
                'sitio_web'    => null,
                'lat'          => -34.5570,
                'lng'          => -58.4600,
                'horarios'     => [
                    ['dia_inicio' => 'Lunes',   'dia_fin' => 'Sábado', 'apertura' => '10:00', 'cierre' => '21:00', 'cerrado' => false],
                    ['dia_inicio' => 'Domingo', 'dia_fin' => null,     'apertura' => '14:00', 'cierre' => '20:00', 'cerrado' => false],
                ],
                'featured'     => false,
                'activo'       => true,
                'plan'         => 'gratuito',
                'categoria'    => 'indumentaria-y-calzado',
                'zona'         => 'belgrano',
            ],
        ];

        foreach ($negocios as $data) {
            $categoriaSlug = $data['categoria'];
            $zonaSlug      = $data['zona'];
            unset($data['categoria'], $data['zona']);

            Negocio::create(array_merge($data, [
                'categoria_id' => $categorias[$categoriaSlug],
                'zona_id'      => $zonas[$zonaSlug],
            ]));
        }
    }
}
